import Head from 'next/head'
import Button from '@/components/Button';
import styled from 'styled-components';

const Title = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Tennessee Harm Reduction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title> My blog </Title> 
        <Button
          size = "lg"
          bgColor = "black"
        > What is Harm Reduction? </Button> 
        <Button
          size = "sm"
          bgColor = "white"
        > Click here to learn more about the meaning of Harm Reduction </Button> 
        <Button
          size = "sm"
        > learn more </Button>
      </main>
    </>
  )
}
