import styled from "styled-components";
import Head from "next/head";
import Button from "@/components/Button";


import ServiceHeroComponent from "@/components/Service/ServiceHeroComponent";

import MoreInformationComp from "@/components/Service/MoreInformationComp";


import Service from "@/components/Service/Service";



const service = () => {
  return (
    <>
      <Head>
        <title>Tennessee Harm Reduction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <ServiceHeroComponent
         h1Text2='support'
         coloredText='&'
         h1Text='Service'
         pText="A charity non-profit organisation that offers health education and harm reduction services to some of Tennessee's most vulnerable and underserved citizens." 
         buttonText="What is Harm Reduction?"
         imgSrc="/SupportHands.png"
         imgAltText="Hero Img"
         imgHeight= "509"
         imgWidth="729"
         buttonSize='lg'
         buttonBgColor='var(--clr-primary-400)'
         buttonFontColor='white'>

         </ServiceHeroComponent>

          <Service/>
          <MoreInformationComp/>
     
      </main>
    </>
  );
};

export default service;


