import styled from "styled-components";
import Head from "next/head";
import Button from "@/components/Button";


import ServiceHeroComponent from "@/components/Service/ServiceHeroComponent";
import ResourcesHero from "@/components/Resources/ResourcesHero";


import TopImagesContainer from "@/components/Service/TopImagesContainer";
import BottomImagesContainer from "@/components/Service/BottomImagesContainer";
import MoreInformationComp from "@/components/Service/MoreInformationComp";


const MainServiceContainer = styled.div`
  border: 10px solid red;
  background-color: red;
  width: 500px;
  height:500px;
`

const service = () => {
  return (
    <>
      <Head>
        <title>Tennessee Harm Reduction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <ServiceHeroComponent
         h1Text2='support'
         coloredText='&'
         h1Text='Service'
         pText="A charity non-profit organisation that offers health education and harm reduction services to some of Tennessee's most vulnerable and underserved citizens." 
         buttonText="What is Harm Reduction?"
         imgSrc="/SupportHands.png"
         imgAltText="Hero Img"
         imgHeight= "509"
         imgWidth="729"
         buttonSize='lg'
         buttonBgColor='var(--clr-primary-400)'
         buttonFontColor='white'></ServiceHeroComponent>

        
          <TopImagesContainer
          // Upper left card
           h1Text1='Provide Supply'
           paraText1="A demand-driven or a participant-driven model travel around  Tennessee doing outreach harm reduction supply"
           buttonText1='FREE access of Syringes'
           buttonText2='FREE access of Naloxone'

           buttonSize='lg'
           buttonBgColor='var(--clr-primary-400)'
           buttonFontColor='yellow'

           // Upper right card
           h1Text2='Supply by Mail'
           paraText2=" Sending free NARCAN kits, syringes, and fentanyl test strips by mail within whole United state to improving the health and welfare of Tennesseans who use drugs."
           buttonText3='FREE access of Syringes'
           buttonText4='FREE access of Naloxone'

         
       
           ></TopImagesContainer>



        <BottomImagesContainer
        // Lower left card
        h1Text3='Treatment program'
        paraText3="Connect with different supporting programs and committee around Tennessee regarding harm reduction support."
        buttonText1='FREE access of Syringes'
        buttonText2='FREE access of Naloxone'

        buttonSize='lg'
        buttonBgColor='var(--clr-primary-400)'
        buttonFontColor='yellow'

        // Lower right card
        h1Text4='Information centre'
        paraText4="Getting the most update information, including getting resources on safer drug use and knowing how to respond in the event of an overdose."
       

       
        ></BottomImagesContainer>
        
         
          <MoreInformationComp></MoreInformationComp>
     
      </main>
    </>
  );
};

export default service;



// -----testing starts here-----------



// const service = () => {
//   return (
//     <>
   
//       <ResourcesHero
      
//       ></ResourcesHero>
//     </>
//   )
// }

// export default service