import Head from "next/head";
import HeroComponent from "@/components/HeroComponent/HeroComponent";

export default function whatisharmreduction() {
    return (
      <>
        <Head>
          <title>Tennessee Harm Reduction</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <main>
          <HeroComponent
            coloredText="What is"
            h1Text="Harm Reduction?"
            pText="Harm reduction is a set of doable tactics and concepts designed to lessen the unfavourable effects of drug usage. The belief in and respect for the rights of drug users is the foundation of the harm reduction movement, which is also a social justice movement." 
            buttonText="learn more"
            imgSrc="/whrHero.png"
            imgAltText="Hero Img"
            imgHeight= "509"
            imgWidth="729"
          />
        </main>
      </>
    );
  }
  